buildscript {
    repositories {
        if (System.getenv('GITHUB_ACTIONS') != 'true') {
            maven { url 'https://maven.aliyun.com/repository/public/' }
            maven { url 'https://maven.aliyun.com/repository/google/' }
            maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
    }
}

allprojects {
    repositories {
        if (System.getenv('GITHUB_ACTIONS') != 'true') {
            maven { url 'https://maven.aliyun.com/repository/public/' }
            maven { url 'https://maven.aliyun.com/repository/google/' }
            maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
            maven { url 'https://storage.flutter-io.cn/download.flutter.io' }
        }
        google()
        mavenCentral()
        if (System.getenv('GITHUB_ACTIONS') == 'true') {
            maven { url 'https://storage.googleapis.com/download.flutter.io' }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
